### Load necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Load files

In [2]:
df_men = pd.read_csv("../data/MRegularSeasonDetailedResults.csv")
df_women = pd.read_csv("../data/WRegularSeasonDetailedResults.csv")

In [46]:
print("Men regular season detailed range:")
print(df_men["Season"].min(), df_men["Season"].max())

print("Women regular season detailed range:")
print(df_women["Season"].min(), df_women["Season"].max())

Men regular season detailed range:
2003 2026
Women regular season detailed range:
2010 2026

### Renaming files to increase readability

In [3]:
headers_rename = {

    # Winner team stats
    "WFGM":  "W_FieldGoalsMade",
    "WFGA":  "W_FieldGoalsAttempted",
    "WFGM3": "W_ThreePointsMade",
    "WFGA3": "W_ThreePointsAttempted",
    "WFTM":  "W_FreeThrowsMade",
    "WFTA":  "W_FreeThrowsAttempted",
    "WOR":   "W_OffensiveRebounds",
    "WDR":   "W_DefensiveRebounds",
    "WAst":  "W_Assists",
    "WTO":   "W_Turnovers",
    "WStl":  "W_Steals",
    "WBlk":  "W_Blocks",
    "WPF":   "W_PersonalFouls",

    # Losing team stats
    "LFGM":  "L_FieldGoalsMade",
    "LFGA":  "L_FieldGoalsAttempted",
    "LFGM3": "L_ThreePointsMade",
    "LFGA3": "L_ThreePointsAttempted",
    "LFTM":  "L_FreeThrowsMade",
    "LFTA":  "L_FreeThrowsAttempted",
    "LOR":   "L_OffensiveRebounds",
    "LDR":   "L_DefensiveRebounds",
    "LAst":  "L_Assists",
    "LTO":   "L_Turnovers",
    "LStl":  "L_Steals",
    "LBlk":  "L_Blocks",
    "LPF":   "L_PersonalFouls"
}

In [4]:
df_men = df_men.rename(columns = headers_rename)
df_men.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [5]:
df_women.rename(columns = headers_rename, inplace = True)
df_women.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
0,2010,11,3103,63,3237,49,H,0,23,54,...,13,6,10,11,27,11,23,7,6,19
1,2010,11,3104,73,3399,68,N,0,26,62,...,21,14,27,14,26,7,20,4,2,27
2,2010,11,3110,71,3224,59,A,0,29,62,...,14,19,23,17,23,8,15,6,0,15
3,2010,11,3111,63,3267,58,A,0,27,52,...,26,16,25,22,22,15,11,14,5,14
4,2010,11,3119,74,3447,70,H,1,30,74,...,17,11,21,21,32,12,14,4,2,14

In [6]:
df_men.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,W_ThreePointsMade,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
count,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,...,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000
mean,2014.622464,70.012674,1288.454653,76.080855,1283.434079,64.060827,0.068589,26.467457,55.858009,7.396669,...,20.285001,12.117614,17.766361,10.391236,21.578408,11.429664,13.801377,6.008748,2.873264,19.267049
std,6.784957,35.928210,105.480339,11.051733,104.986587,10.876749,0.304631,4.691850,7.447786,3.139463,...,6.108233,5.359096,7.084354,4.209703,4.516139,3.730345,4.383176,2.743815,2.016967,4.551296
min,2003.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000,10.000000,26.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.000000
25%,2009.000000,38.000000,1199.000000,68.000000,1192.000000,57.000000,0.000000,23.000000,51.000000,5.000000,...,16.000000,8.000000,13.000000,7.000000,18.000000,9.000000,11.000000,4.000000,1.000000,16.000000
50%,2015.000000,73.000000,1287.000000,76.000000,1282.000000,64.000000,0.000000,26.000000,56.000000,7.000000,...,20.000000,12.000000,17.000000,10.000000,21.000000,11.000000,13.000000,6.000000,3.000000,19.000000
75%,2020.000000,101.000000,1382.000000,83.000000,1374.000000,71.000000,0.000000,29.000000,61.000000,9.000000,...,24.000000,15.000000,22.000000,13.000000,25.000000,14.000000,17.000000,8.000000,4.000000,22.000000
max,2026.000000,132.000000,1481.000000,149.000000,1481.000000,144.000000,6.000000,57.000000,103.000000,26.000000,...,59.000000,48.000000,65.000000,36.000000,49.000000,31.000000,41.000000,22.000000,18.000000,45.000000

In [7]:
df_women.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,W_ThreePointsMade,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
count,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,...,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000
mean,2017.882416,68.827858,3285.435904,71.804163,3286.980492,57.258687,0.051412,25.885796,58.999474,6.316707,...,17.999836,10.502754,15.480580,11.209964,22.319935,10.929770,17.120484,7.112274,2.814631,18.174352
std,4.856439,36.312736,104.259376,11.567866,105.788375,10.945184,0.258102,4.991710,7.970657,3.131598,...,6.455423,4.930955,6.622443,4.635878,4.938710,3.803927,5.276003,3.191684,2.058725,4.558495
min,2010.000000,0.000000,3101.000000,30.000000,3101.000000,11.000000,0.000000,9.000000,30.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,3.000000
25%,2014.000000,34.000000,3196.000000,64.000000,3195.000000,50.000000,0.000000,22.000000,53.000000,4.000000,...,13.000000,7.000000,11.000000,8.000000,19.000000,8.000000,13.000000,5.000000,1.000000,15.000000
50%,2018.000000,72.000000,3283.000000,71.000000,3287.000000,57.000000,0.000000,25.000000,59.000000,6.000000,...,18.000000,10.000000,15.000000,11.000000,22.000000,11.000000,17.000000,7.000000,2.000000,18.000000
75%,2022.000000,100.000000,3377.000000,79.000000,3378.000000,64.000000,0.000000,29.000000,64.000000,8.000000,...,22.000000,14.000000,20.000000,14.000000,26.000000,13.000000,20.000000,9.000000,4.000000,21.000000
max,2026.000000,132.000000,3481.000000,140.000000,3481.000000,130.000000,5.000000,58.000000,113.000000,30.000000,...,80.000000,37.000000,52.000000,38.000000,53.000000,34.000000,49.000000,26.000000,21.000000,47.000000

## Rebound and margin features
The same calculations are applied to both the men's and women's datasets.

### Features included

#### Total Rebounds @Dan
`TRB = OR + DR`

#### Rebound Percentage @Dan
`REB% = REB / (REB + OppREB)`

#### Offensive Rebound Percentage @Dan
`OREB% = OREB / (OREB + OppDREB)`

#### Defensive Rebound Percentage @Dan
`DREB% = DREB / (DREB + OppOREB)`

#### Turnover Margin @Gabe
`TurnoverMargin = OpponentTurnovers - TeamTurnovers`

#### Rebound Margin @Gabe
`ReboundMargin = TeamTotalRebounds - OpponentTotalRebounds`

In [8]:
def add_rebound_margin_features(df):
    df = df.copy()

    df["W_TotalRebounds"] = df["W_OffensiveRebounds"] + df["W_DefensiveRebounds"]
    df["L_TotalRebounds"] = df["L_OffensiveRebounds"] + df["L_DefensiveRebounds"]

    df["W_ReboundPct"] = df["W_TotalRebounds"] / (
            df["W_TotalRebounds"] + df["L_TotalRebounds"]
    )
    df["L_ReboundPct"] = df["L_TotalRebounds"] / (
            df["W_TotalRebounds"] + df["L_TotalRebounds"]
    )

    df["W_OffensiveReboundPct"] = df["W_OffensiveRebounds"] / (
            df["W_OffensiveRebounds"] + df["L_DefensiveRebounds"]
    )
    df["L_OffensiveReboundPct"] = df["L_OffensiveRebounds"] / (
            df["L_OffensiveRebounds"] + df["W_DefensiveRebounds"]
    )

    df["W_DefensiveReboundPct"] = df["W_DefensiveRebounds"] / (
            df["W_DefensiveRebounds"] + df["L_OffensiveRebounds"]
    )
    df["L_DefensiveReboundPct"] = df["L_DefensiveRebounds"] / (
            df["L_DefensiveRebounds"] + df["W_OffensiveRebounds"]
    )

    df["W_TurnoverMargin"] = df["L_Turnovers"] - df["W_Turnovers"]
    df["L_TurnoverMargin"] = df["W_Turnovers"] - df["L_Turnovers"]

    df["W_ReboundMargin"] = df["W_TotalRebounds"] - df["L_TotalRebounds"]
    df["L_ReboundMargin"] = df["L_TotalRebounds"] - df["W_TotalRebounds"]

    return df

In [9]:
df_men = add_rebound_margin_features(df_men)
df_women = add_rebound_margin_features(df_women)

In [10]:
winner_df = pd.DataFrame({
    "Season": df_men["Season"],
    "DayNum": df_men["DayNum"],
    "NumOT": df_men["NumOT"],
    "TeamID": df_men["WTeamID"],
    "OpponentID": df_men["LTeamID"],
    "Win": 1,
    "PointsFor": df_men["WScore"],
    "PointsAgainst": df_men["LScore"],
    "FieldGoalsMade": df_men["W_FieldGoalsMade"],
    "FieldGoalsAttempted": df_men["W_FieldGoalsAttempted"],
    "ThreePointsMade": df_men["W_ThreePointsMade"],
    "ThreePointsAttempted": df_men["W_ThreePointsAttempted"],
    "FreeThrowsMade": df_men["W_FreeThrowsMade"],
    "FreeThrowsAttempted": df_men["W_FreeThrowsAttempted"],
    "OffensiveRebounds": df_men["W_OffensiveRebounds"],
    "DefensiveRebounds": df_men["W_DefensiveRebounds"],
    "Assists": df_men["W_Assists"],
    "Turnovers": df_men["W_Turnovers"],
    "Steals": df_men["W_Steals"],
    "Blocks": df_men["W_Blocks"],
    "PersonalFouls": df_men["W_PersonalFouls"],
    "TotalRebounds": df_men["W_TotalRebounds"],
    "ReboundPct": df_men["W_ReboundPct"],
    "OffensiveReboundPct": df_men["W_OffensiveReboundPct"],
    "DefensiveReboundPct": df_men["W_DefensiveReboundPct"],
    "OpponentTurnovers": df_men["L_Turnovers"],
    "OpponentTotalRebounds": df_men["L_TotalRebounds"],
    "TurnoverMargin": df_men["W_TurnoverMargin"],
    "ReboundMargin": df_men["W_ReboundMargin"],
})

winner_df_women = pd.DataFrame({
    "Season": df_women["Season"],
    "DayNum": df_women["DayNum"],
    "NumOT": df_women["NumOT"],
    "TeamID": df_women["WTeamID"],
    "OpponentID": df_women["LTeamID"],
    "Win": 1,
    "PointsFor": df_women["WScore"],
    "PointsAgainst": df_women["LScore"],
    "FieldGoalsMade": df_women["W_FieldGoalsMade"],
    "FieldGoalsAttempted": df_women["W_FieldGoalsAttempted"],
    "ThreePointsMade": df_women["W_ThreePointsMade"],
    "ThreePointsAttempted": df_women["W_ThreePointsAttempted"],
    "FreeThrowsMade": df_women["W_FreeThrowsMade"],
    "FreeThrowsAttempted": df_women["W_FreeThrowsAttempted"],
    "OffensiveRebounds": df_women["W_OffensiveRebounds"],
    "DefensiveRebounds": df_women["W_DefensiveRebounds"],
    "Assists": df_women["W_Assists"],
    "Turnovers": df_women["W_Turnovers"],
    "Steals": df_women["W_Steals"],
    "Blocks": df_women["W_Blocks"],
    "PersonalFouls": df_women["W_PersonalFouls"],
    "TotalRebounds": df_women["W_TotalRebounds"],
    "ReboundPct": df_women["W_ReboundPct"],
    "OffensiveReboundPct": df_women["W_OffensiveReboundPct"],
    "DefensiveReboundPct": df_women["W_DefensiveReboundPct"],
    "OpponentTurnovers": df_women["L_Turnovers"],
    "OpponentTotalRebounds": df_women["L_TotalRebounds"],
    "TurnoverMargin": df_women["W_TurnoverMargin"],
    "ReboundMargin": df_women["W_ReboundMargin"],
})

In [11]:
loser_df = pd.DataFrame({
    "Season": df_men["Season"],
    "DayNum": df_men["DayNum"],
    "NumOT": df_men["NumOT"],
    "TeamID": df_men["LTeamID"],
    "OpponentID": df_men["WTeamID"],
    "Win": 0,
    "PointsFor": df_men["LScore"],
    "PointsAgainst": df_men["WScore"],
    "FieldGoalsMade": df_men["L_FieldGoalsMade"],
    "FieldGoalsAttempted": df_men["L_FieldGoalsAttempted"],
    "ThreePointsMade": df_men["L_ThreePointsMade"],
    "ThreePointsAttempted": df_men["L_ThreePointsAttempted"],
    "FreeThrowsMade": df_men["L_FreeThrowsMade"],
    "FreeThrowsAttempted": df_men["L_FreeThrowsAttempted"],
    "OffensiveRebounds": df_men["L_OffensiveRebounds"],
    "DefensiveRebounds": df_men["L_DefensiveRebounds"],
    "Assists": df_men["L_Assists"],
    "Turnovers": df_men["L_Turnovers"],
    "Steals": df_men["L_Steals"],
    "Blocks": df_men["L_Blocks"],
    "PersonalFouls": df_men["L_PersonalFouls"],
    "TotalRebounds": df_men["L_TotalRebounds"],
    "ReboundPct": df_men["L_ReboundPct"],
    "OffensiveReboundPct": df_men["L_OffensiveReboundPct"],
    "DefensiveReboundPct": df_men["L_DefensiveReboundPct"],
    "OpponentTurnovers": df_men["W_Turnovers"],
    "OpponentTotalRebounds": df_men["W_TotalRebounds"],
    "TurnoverMargin": df_men["L_TurnoverMargin"],
    "ReboundMargin": df_men["L_ReboundMargin"],
})

loser_df_women = pd.DataFrame({
    "Season": df_women["Season"],
    "DayNum": df_women["DayNum"],
    "NumOT": df_women["NumOT"],
    "TeamID": df_women["LTeamID"],
    "OpponentID": df_women["WTeamID"],
    "Win": 0,
    "PointsFor": df_women["LScore"],
    "PointsAgainst": df_women["WScore"],
    "FieldGoalsMade": df_women["L_FieldGoalsMade"],
    "FieldGoalsAttempted": df_women["L_FieldGoalsAttempted"],
    "ThreePointsMade": df_women["L_ThreePointsMade"],
    "ThreePointsAttempted": df_women["L_ThreePointsAttempted"],
    "FreeThrowsMade": df_women["L_FreeThrowsMade"],
    "FreeThrowsAttempted": df_women["L_FreeThrowsAttempted"],
    "OffensiveRebounds": df_women["L_OffensiveRebounds"],
    "DefensiveRebounds": df_women["L_DefensiveRebounds"],
    "Assists": df_women["L_Assists"],
    "Turnovers": df_women["L_Turnovers"],
    "Steals": df_women["L_Steals"],
    "Blocks": df_women["L_Blocks"],
    "PersonalFouls": df_women["L_PersonalFouls"],
    "TotalRebounds": df_women["L_TotalRebounds"],
    "ReboundPct": df_women["L_ReboundPct"],
    "OffensiveReboundPct": df_women["L_OffensiveReboundPct"],
    "DefensiveReboundPct": df_women["L_DefensiveReboundPct"],
    "OpponentTurnovers": df_women["W_Turnovers"],
    "OpponentTotalRebounds": df_women["W_TotalRebounds"],
    "TurnoverMargin": df_women["L_TurnoverMargin"],
    "ReboundMargin": df_women["L_ReboundMargin"],
})

According to previous winners, score marging is a good and strong indicator on team's potential to win. It's calculated by the difference in points scored between a team and its oppnents over a season.

In [12]:
winner_df["MarginScore"] = winner_df["PointsFor"] - winner_df["PointsAgainst"]
loser_df["MarginScore"] = loser_df["PointsFor"] - loser_df["PointsAgainst"]

winner_df_women["MarginScore"] = winner_df_women["PointsFor"] - winner_df_women["PointsAgainst"]
loser_df_women["MarginScore"] = loser_df_women["PointsFor"] - loser_df_women["PointsAgainst"]

In [13]:
games_men = pd.concat([winner_df, loser_df], ignore_index=True)
games_women = pd.concat([winner_df_women, loser_df_women], ignore_index=True)

## Advanced team game statistics

This section applies the same game-level feature calculations to both the men's and women's datasets after merging winner and loser rows into one long-format dataframe.

The goal here is not to change the structure of the notebook, but to avoid repeating the same calculations twice.

### Stats included in this function

#### Field Goal Percentage @Gabe
`FG% = FGM / FGA`

#### 3-Point Percentage @Gabe
`3P% = 3PM / 3PA`

#### Free Throw Percentage @Gabe
`FT% = FTM / FTA`

#### Turnover Percentage @Gabe
`TO% = TO / (FGA + 0.44 * FTA + TO)`

#### Assist-to-Turnover Ratio @Gabe
`AST/TO = AST / TO`

#### Total Game Points @Gabe
`GameTotalPoints = PointsFor + PointsAgainst`

#### Possessions @Hafsa
`Poss = FGA - OR + TO + 0.44 * FTA`

#### Offensive Efficiency @Hafsa
`OffEfficiency = PointsFor / Possessions`

#### Defensive Efficiency @Hafsa
`DefEfficiency = PointsAgainst / Possessions`

#### Net Rating @Hafsa
`NetRating = OffEfficiency - DefEfficiency`

#### Games Played @Gabe
`GamesPlayed = total number of games played by team in a season`

#### Wins @Gabe
`Wins = total number of wins by team in a season`

#### Win Percentage @Gabe
`Win% = Wins / GamesPlayed`

#### Losses @Gabe
`Losses = GamesPlayed - Wins`

#### Loss Percentage @Gabe
`Loss% = Losses / GamesPlayed`

In [14]:
def add_advanced_stats(df):
    df = df.copy()

    df["FieldGoalsPct"] = df["FieldGoalsMade"] / df["FieldGoalsAttempted"]
    df["ThreePointsMadePct"] = df["ThreePointsMade"] / df["ThreePointsAttempted"]
    df["FreeThrowPct"] = df["FreeThrowsMade"] / df["FreeThrowsAttempted"]

    df["TurnoverPct"] = df["Turnovers"] / (
            df["FieldGoalsAttempted"] + 0.44 * df["FreeThrowsAttempted"] + df["Turnovers"]
    )

    df["AssistTurnoverRto"] = df["Assists"] / df["Turnovers"]
    df["GameTotalPoints"] = df["PointsAgainst"] + df["PointsFor"]

    df["Possessions"] = (
            df["FieldGoalsAttempted"]
            - df["OffensiveRebounds"]
            + df["Turnovers"]
            + 0.44 * df["FreeThrowsAttempted"]
    )

    df["OffEfficiency"] = df["PointsFor"] / df["Possessions"]
    df["DefEfficiency"] = df["PointsAgainst"] / df["Possessions"]
    df["NetRating"] = df["OffEfficiency"] - df["DefEfficiency"]

    df["GamesPlayed"] = df.groupby(["Season", "TeamID"])["Win"].transform("count")
    df["Wins"] = df.groupby(["Season", "TeamID"])["Win"].transform("sum")
    df["WinPct"] = df["Wins"] / df["GamesPlayed"]

    df["Losses"] = df["GamesPlayed"] - df["Wins"]
    df["LossPct"] = df["Losses"] / df["GamesPlayed"]

    return df

In [15]:
games_men = add_advanced_stats(games_men)
games_women = add_advanced_stats(games_women)

This section aggregates the long-format game logs into one row per team per season.

The goal is to summarize each team's regular season performance using average game-level statistics and season-level win/loss information.

### Men's team-season feature table

In [16]:
team_features_men = games_men.groupby([
    "Season",
    "TeamID"
], as_index=False).agg({
    "Win": ["sum", "count"],
    "PointsFor": "mean",
    "PointsAgainst": "mean",
    "MarginScore": ["mean", "std"],
    "NumOT": "mean",
    "FieldGoalsMade": "mean",
    "FieldGoalsAttempted": "mean",
    "FieldGoalsPct": "mean",
    "ThreePointsMade": "mean",
    "ThreePointsAttempted": "mean",
    "ThreePointsMadePct": "mean",
    "FreeThrowsMade": "mean",
    "FreeThrowsAttempted": "mean",
    "FreeThrowPct": "mean",
    "OffensiveRebounds": "mean",
    "DefensiveRebounds": "mean",
    "TotalRebounds": "mean",
    "ReboundPct": "mean",
    "OffensiveReboundPct": "mean",
    "DefensiveReboundPct": "mean",
    "Assists": "mean",
    "Turnovers": "mean",
    "TurnoverPct": "mean",
    "AssistTurnoverRto": "mean",
    "Steals": "mean",
    "Blocks": "mean",
    "PersonalFouls": "mean",
    "TurnoverMargin": "mean",
    "ReboundMargin": "mean",
    "Possessions": "mean",
    "OffEfficiency": "mean",
    "DefEfficiency": "mean",
    "NetRating": "mean",
    "GameTotalPoints": "mean",
})

In [17]:
team_features_men.columns = [
    "Season",
    "TeamID",
    "Wins",
    "GamesPlayed",
    "AvgPointsFor",
    "AvgPointsAgainst",
    "AvgMarginScore",
    "MarginScoreStd",
    "AvgNumOT",
    "AvgFieldGoalsMade",
    "AvgFieldGoalsAttempted",
    "AvgFieldGoalsPct",
    "AvgThreePointsMade",
    "AvgThreePointsAttempted",
    "AvgThreePointsPct",
    "AvgFreeThrowsMade",
    "AvgFreeThrowsAttempted",
    "AvgFreeThrowPct",
    "AvgOffensiveRebounds",
    "AvgDefensiveRebounds",
    "AvgTotalRebounds",
    "AvgReboundPct",
    "AvgOffensiveReboundPct",
    "AvgDefensiveReboundPct",
    "AvgAssists",
    "AvgTurnovers",
    "AvgTurnoverPct",
    "AvgAssistTurnoverRto",
    "AvgSteals",
    "AvgBlocks",
    "AvgPersonalFouls",
    "AvgTurnoverMargin",
    "AvgReboundMargin",
    "AvgPossessions",
    "AvgOffEfficiency",
    "AvgDefEfficiency",
    "AvgNetRating",
    "AvgGameTotalPoints"
]

In [18]:
team_features_men["Losses"] = team_features_men["GamesPlayed"] - team_features_men["Wins"]
team_features_men["WinPct"] = team_features_men["Wins"] / team_features_men["GamesPlayed"]
team_features_men["LossPct"] = team_features_men["Losses"] / team_features_men["GamesPlayed"]

team_features_men.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgTurnoverMargin,AvgReboundMargin,AvgPossessions,AvgOffEfficiency,AvgDefEfficiency,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct
0,2003,1102,12,28,57.250000,57.000000,0.250000,16.169530,0.000000,19.142857,...,1.535714,-8.750000,54.562857,1.049026,1.045665,0.003361,114.250000,16,0.428571,0.571429
1,2003,1103,13,27,78.777778,78.148148,0.629630,11.337983,0.296296,27.148148,...,2.703704,-4.370370,70.078519,1.119851,1.116327,0.003524,156.925926,14,0.481481,0.518519
2,2003,1104,17,28,69.285714,65.000000,4.285714,13.391145,0.035714,24.035714,...,0.571429,3.964286,66.101429,1.045276,0.986530,0.058746,134.285714,11,0.607143,0.392857
3,2003,1105,7,26,71.769231,76.653846,-4.884615,15.860207,0.153846,24.384615,...,0.153846,-2.961538,76.381538,0.939422,1.005283,-0.065861,148.423077,19,0.269231,0.730769
4,2003,1106,13,28,63.607143,63.750000,-0.142857,12.601335,0.035714,23.428571,...,-1.964286,2.464286,67.280000,0.944691,0.948608,-0.003917,127.357143,15,0.464286,0.535714

### Women's team-season feature table

In [19]:
team_features_women = games_women.groupby([
    "Season",
    "TeamID"
], as_index=False).agg({
    "Win": ["sum", "count"],
    "PointsFor": "mean",
    "PointsAgainst": "mean",
    "MarginScore": ["mean", "std"],
    "NumOT": "mean",
    "FieldGoalsMade": "mean",
    "FieldGoalsAttempted": "mean",
    "FieldGoalsPct": "mean",
    "ThreePointsMade": "mean",
    "ThreePointsAttempted": "mean",
    "ThreePointsMadePct": "mean",
    "FreeThrowsMade": "mean",
    "FreeThrowsAttempted": "mean",
    "FreeThrowPct": "mean",
    "OffensiveRebounds": "mean",
    "DefensiveRebounds": "mean",
    "TotalRebounds": "mean",
    "ReboundPct": "mean",
    "OffensiveReboundPct": "mean",
    "DefensiveReboundPct": "mean",
    "Assists": "mean",
    "Turnovers": "mean",
    "TurnoverPct": "mean",
    "AssistTurnoverRto": "mean",
    "Steals": "mean",
    "Blocks": "mean",
    "PersonalFouls": "mean",
    "TurnoverMargin": "mean",
    "ReboundMargin": "mean",
    "Possessions": "mean",
    "OffEfficiency": "mean",
    "DefEfficiency": "mean",
    "NetRating": "mean",
    "GameTotalPoints": "mean",
})

In [20]:
team_features_women.columns = [
    "Season",
    "TeamID",
    "Wins",
    "GamesPlayed",
    "AvgPointsFor",
    "AvgPointsAgainst",
    "AvgMarginScore",
    "MarginScoreStd",
    "AvgNumOT",
    "AvgFieldGoalsMade",
    "AvgFieldGoalsAttempted",
    "AvgFieldGoalsPct",
    "AvgThreePointsMade",
    "AvgThreePointsAttempted",
    "AvgThreePointsPct",
    "AvgFreeThrowsMade",
    "AvgFreeThrowsAttempted",
    "AvgFreeThrowPct",
    "AvgOffensiveRebounds",
    "AvgDefensiveRebounds",
    "AvgTotalRebounds",
    "AvgReboundPct",
    "AvgOffensiveReboundPct",
    "AvgDefensiveReboundPct",
    "AvgAssists",
    "AvgTurnovers",
    "AvgTurnoverPct",
    "AvgAssistTurnoverRto",
    "AvgSteals",
    "AvgBlocks",
    "AvgPersonalFouls",
    "AvgTurnoverMargin",
    "AvgReboundMargin",
    "AvgPossessions",
    "AvgOffEfficiency",
    "AvgDefEfficiency",
    "AvgNetRating",
    "AvgGameTotalPoints"
]

In [21]:
team_features_women["Losses"] = team_features_women["GamesPlayed"] - team_features_women["Wins"]
team_features_women["WinPct"] = team_features_women["Wins"] / team_features_women["GamesPlayed"]
team_features_women["LossPct"] = team_features_women["Losses"] / team_features_women["GamesPlayed"]

team_features_women.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgTurnoverMargin,AvgReboundMargin,AvgPossessions,AvgOffEfficiency,AvgDefEfficiency,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct
0,2010,3102,1,28,51.821429,71.785714,-19.964286,14.662833,0.000000,19.142857,...,-3.321429,-4.678571,64.207143,0.807968,1.122724,-0.314756,123.607143,27,0.035714,0.964286
1,2010,3103,17,30,62.233333,59.633333,2.600000,15.477681,0.033333,22.233333,...,0.433333,2.533333,67.957333,0.918210,0.879679,0.038530,121.866667,13,0.566667,0.433333
2,2010,3104,11,29,64.137931,67.000000,-2.862069,18.502363,0.103448,24.724138,...,0.068966,-0.931034,74.182069,0.863327,0.903819,-0.040492,131.137931,18,0.379310,0.620690
3,2010,3105,14,27,60.777778,64.740741,-3.962963,14.468750,0.000000,20.370370,...,-4.296296,0.555556,72.928889,0.833714,0.890943,-0.057229,125.518519,13,0.518519,0.481481
4,2010,3106,12,29,55.137931,57.413793,-2.275862,11.572432,0.034483,18.448276,...,-1.793103,3.965517,68.663448,0.804714,0.833093,-0.028379,112.551724,17,0.413793,0.586207

## Conference features

In [22]:
m_conf = pd.read_csv("../data/MTeamConferences.csv")
w_conf = pd.read_csv("../data/WTeamConferences.csv")

In [23]:
team_features_men = team_features_men.merge(
    m_conf[["Season", "TeamID", "ConfAbbrev"]],
    on=["Season", "TeamID"],
    how="left"
)
team_features_men.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgReboundMargin,AvgPossessions,AvgOffEfficiency,AvgDefEfficiency,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct,ConfAbbrev
0,2003,1102,12,28,57.250000,57.000000,0.250000,16.169530,0.000000,19.142857,...,-8.750000,54.562857,1.049026,1.045665,0.003361,114.250000,16,0.428571,0.571429,mwc
1,2003,1103,13,27,78.777778,78.148148,0.629630,11.337983,0.296296,27.148148,...,-4.370370,70.078519,1.119851,1.116327,0.003524,156.925926,14,0.481481,0.518519,mac
2,2003,1104,17,28,69.285714,65.000000,4.285714,13.391145,0.035714,24.035714,...,3.964286,66.101429,1.045276,0.986530,0.058746,134.285714,11,0.607143,0.392857,sec
3,2003,1105,7,26,71.769231,76.653846,-4.884615,15.860207,0.153846,24.384615,...,-2.961538,76.381538,0.939422,1.005283,-0.065861,148.423077,19,0.269231,0.730769,swac
4,2003,1106,13,28,63.607143,63.750000,-0.142857,12.601335,0.035714,23.428571,...,2.464286,67.280000,0.944691,0.948608,-0.003917,127.357143,15,0.464286,0.535714,swac

In [24]:
team_features_women = team_features_women.merge(
    w_conf[["Season", "TeamID", "ConfAbbrev"]],
    on=["Season", "TeamID"],
    how="left"
)
team_features_women.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgReboundMargin,AvgPossessions,AvgOffEfficiency,AvgDefEfficiency,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct,ConfAbbrev
0,2010,3102,1,28,51.821429,71.785714,-19.964286,14.662833,0.000000,19.142857,...,-4.678571,64.207143,0.807968,1.122724,-0.314756,123.607143,27,0.035714,0.964286,mwc
1,2010,3103,17,30,62.233333,59.633333,2.600000,15.477681,0.033333,22.233333,...,2.533333,67.957333,0.918210,0.879679,0.038530,121.866667,13,0.566667,0.433333,mac
2,2010,3104,11,29,64.137931,67.000000,-2.862069,18.502363,0.103448,24.724138,...,-0.931034,74.182069,0.863327,0.903819,-0.040492,131.137931,18,0.379310,0.620690,sec
3,2010,3105,14,27,60.777778,64.740741,-3.962963,14.468750,0.000000,20.370370,...,0.555556,72.928889,0.833714,0.890943,-0.057229,125.518519,13,0.518519,0.481481,swac
4,2010,3106,12,29,55.137931,57.413793,-2.275862,11.572432,0.034483,18.448276,...,3.965517,68.663448,0.804714,0.833093,-0.028379,112.551724,17,0.413793,0.586207,swac

## Seeds

In [25]:
m_seeds = pd.read_csv("../data/MNCAATourneySeeds.csv")
w_seeds = pd.read_csv("../data/WNCAATourneySeeds.csv")

In [26]:
def extract_seed_number(seed_value):
    if pd.isna(seed_value):
        return np.nan

    digits = "".join(ch for ch in str(seed_value) if ch.isdigit())
    return int(digits) if digits else np.nan

In [27]:
m_seeds["SeedNum"] = m_seeds["Seed"].apply(extract_seed_number)
m_seeds["HasTournamentSeed"] = 1

w_seeds["SeedNum"] = w_seeds["Seed"].apply(extract_seed_number)
w_seeds["HasTournamentSeed"] = 1

In [28]:
team_features_men = team_features_men.merge(
    m_seeds[["Season", "TeamID", "Seed", "SeedNum", "HasTournamentSeed"]],
    on=["Season", "TeamID"],
    how="left"
)
team_features_men["HasTournamentSeed"] = team_features_men["HasTournamentSeed"].fillna(0).astype(int)
team_features_men.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgDefEfficiency,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct,ConfAbbrev,Seed,SeedNum,HasTournamentSeed
0,2003,1102,12,28,57.250000,57.000000,0.250000,16.169530,0.000000,19.142857,...,1.045665,0.003361,114.250000,16,0.428571,0.571429,mwc,NaN,NaN,0
1,2003,1103,13,27,78.777778,78.148148,0.629630,11.337983,0.296296,27.148148,...,1.116327,0.003524,156.925926,14,0.481481,0.518519,mac,NaN,NaN,0
2,2003,1104,17,28,69.285714,65.000000,4.285714,13.391145,0.035714,24.035714,...,0.986530,0.058746,134.285714,11,0.607143,0.392857,sec,Y10,10.0,1
3,2003,1105,7,26,71.769231,76.653846,-4.884615,15.860207,0.153846,24.384615,...,1.005283,-0.065861,148.423077,19,0.269231,0.730769,swac,NaN,NaN,0
4,2003,1106,13,28,63.607143,63.750000,-0.142857,12.601335,0.035714,23.428571,...,0.948608,-0.003917,127.357143,15,0.464286,0.535714,swac,NaN,NaN,0

In [29]:
team_features_women = team_features_women.merge(
    w_seeds[["Season", "TeamID", "Seed", "SeedNum", "HasTournamentSeed"]],
    on=["Season", "TeamID"],
    how="left"
)
team_features_women["HasTournamentSeed"] = team_features_women["HasTournamentSeed"].fillna(0).astype(int)
team_features_women.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgDefEfficiency,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct,ConfAbbrev,Seed,SeedNum,HasTournamentSeed
0,2010,3102,1,28,51.821429,71.785714,-19.964286,14.662833,0.000000,19.142857,...,1.122724,-0.314756,123.607143,27,0.035714,0.964286,mwc,NaN,NaN,0
1,2010,3103,17,30,62.233333,59.633333,2.600000,15.477681,0.033333,22.233333,...,0.879679,0.038530,121.866667,13,0.566667,0.433333,mac,NaN,NaN,0
2,2010,3104,11,29,64.137931,67.000000,-2.862069,18.502363,0.103448,24.724138,...,0.903819,-0.040492,131.137931,18,0.379310,0.620690,sec,NaN,NaN,0
3,2010,3105,14,27,60.777778,64.740741,-3.962963,14.468750,0.000000,20.370370,...,0.890943,-0.057229,125.518519,13,0.518519,0.481481,swac,NaN,NaN,0
4,2010,3106,12,29,55.137931,57.413793,-2.275862,11.572432,0.034483,18.448276,...,0.833093,-0.028379,112.551724,17,0.413793,0.586207,swac,NaN,NaN,0

## Massey

In [30]:
m_massey = pd.read_csv("../data/MMasseyOrdinals.csv")

In [31]:
massey_men = m_massey[m_massey["SystemName"] == "MAS"].copy()
massey_men.head()

      Season  RankingDayNum SystemName  TeamID  OrdinalRank
1987    2003             37        MAS    1102           90
1988    2003             37        MAS    1103          188
1989    2003             37        MAS    1104            7
1990    2003             37        MAS    1105          292
1991    2003             37        MAS    1106          263

In [32]:
latest_massey_men = (
    massey_men
    .sort_values(["Season", "TeamID", "RankingDayNum"])
    .groupby(["Season", "TeamID"], as_index=False)
    .tail(1)
)
latest_massey_men.head()

        Season  RankingDayNum SystemName  TeamID  OrdinalRank
126278    2003            133        MAS    1102          172
126279    2003            133        MAS    1103          163
126280    2003            133        MAS    1104           41
126281    2003            133        MAS    1105          310
126282    2003            133        MAS    1106          270

In [33]:
latest_massey_men = latest_massey_men[[
    "Season",
    "TeamID",
    "OrdinalRank"
]].rename(columns={
    "OrdinalRank": "MasseyOrdinalRank"
})
latest_massey_men.head()

        Season  TeamID  MasseyOrdinalRank
126278    2003    1102                172
126279    2003    1103                163
126280    2003    1104                 41
126281    2003    1105                310
126282    2003    1106                270

In [34]:
team_features_men = team_features_men.merge(
    latest_massey_men,
    on=["Season", "TeamID"],
    how="left"
)
team_features_men.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgNetRating,AvgGameTotalPoints,Losses,WinPct,LossPct,ConfAbbrev,Seed,SeedNum,HasTournamentSeed,MasseyOrdinalRank
0,2003,1102,12,28,57.250000,57.000000,0.250000,16.169530,0.000000,19.142857,...,0.003361,114.250000,16,0.428571,0.571429,mwc,NaN,NaN,0,172.0
1,2003,1103,13,27,78.777778,78.148148,0.629630,11.337983,0.296296,27.148148,...,0.003524,156.925926,14,0.481481,0.518519,mac,NaN,NaN,0,163.0
2,2003,1104,17,28,69.285714,65.000000,4.285714,13.391145,0.035714,24.035714,...,0.058746,134.285714,11,0.607143,0.392857,sec,Y10,10.0,1,41.0
3,2003,1105,7,26,71.769231,76.653846,-4.884615,15.860207,0.153846,24.384615,...,-0.065861,148.423077,19,0.269231,0.730769,swac,NaN,NaN,0,310.0
4,2003,1106,13,28,63.607143,63.750000,-0.142857,12.601335,0.035714,23.428571,...,-0.003917,127.357143,15,0.464286,0.535714,swac,NaN,NaN,0,270.0

### Women's Massey ratings (computed from regular season results) @Jason

In [35]:
import sys
sys.path.append("../scripts")
from massey_method import massey_method

In [36]:
w_massey_list = []

for season in sorted(df_women["Season"].unique()):
    season_df = df_women[df_women["Season"] == season]
    ratings, sos, teams = massey_method(season_df)

    season_massey = pd.DataFrame({
        "Season": season,
        "TeamID": list(ratings.keys()),
        "WMasseyRating": list(ratings.values())
    })
    season_massey["WMasseySOS"] = season_massey["TeamID"].map(sos)
    w_massey_list.append(season_massey)

In [37]:
w_massey_df = pd.concat(w_massey_list, ignore_index=True)
w_massey_df.head()

   Season  TeamID  WMasseyRating  WMasseySOS
0    2010    3102     -16.458614    3.505671
1    2010    3103       1.307592   -1.292408
2    2010    3104       3.580140    6.442209
3    2010    3105     -15.328316  -11.365353
4    2010    3106     -14.259312  -11.983450

In [38]:
team_features_women = team_features_women.merge(
    w_massey_df,
    on=["Season", "TeamID"],
    how="left"
)
team_features_women.head()

,Season,TeamID,Wins,GamesPlayed,AvgPointsFor,AvgPointsAgainst,AvgMarginScore,MarginScoreStd,AvgNumOT,AvgFieldGoalsMade,...,AvgGameTotalPoints,Losses,WinPct,LossPct,ConfAbbrev,Seed,SeedNum,HasTournamentSeed,WMasseyRating,WMasseySOS
0,2010,3102,1,28,51.821429,71.785714,-19.964286,14.662833,0.000000,19.142857,...,123.607143,27,0.035714,0.964286,mwc,NaN,NaN,0,-16.458614,3.505671
1,2010,3103,17,30,62.233333,59.633333,2.600000,15.477681,0.033333,22.233333,...,121.866667,13,0.566667,0.433333,mac,NaN,NaN,0,1.307592,-1.292408
2,2010,3104,11,29,64.137931,67.000000,-2.862069,18.502363,0.103448,24.724138,...,131.137931,18,0.379310,0.620690,sec,NaN,NaN,0,3.580140,6.442209
3,2010,3105,14,27,60.777778,64.740741,-3.962963,14.468750,0.000000,20.370370,...,125.518519,13,0.518519,0.481481,swac,NaN,NaN,0,-15.328316,-11.365353
4,2010,3106,12,29,55.137931,57.413793,-2.275862,11.572432,0.034483,18.448276,...,112.551724,17,0.413793,0.586207,swac,NaN,NaN,0,-14.259312,-11.983450

### Checking for missing values

In [39]:
missing_summary_men = (
    team_features_men.isna()
    .mean()
    .sort_values(ascending=False)
)

missing_summary_women = (
    team_features_women.isna()
    .mean()
    .sort_values(ascending=False)
)

In [40]:
print("Men missing-value summary")
print(missing_summary_men[missing_summary_men > 0])

print()
print("Women missing-value summary")
print(missing_summary_women[missing_summary_women > 0])

Men missing-value summary
Seed                 0.823628
SeedNum              0.823628
MasseyOrdinalRank    0.162832
dtype: float64

Women missing-value summary
Seed       0.836379
SeedNum    0.836379
dtype: float64

### Replace infinite values

In [41]:
numeric_cols_men = team_features_men.select_dtypes(include=[np.number]).columns
team_features_men[numeric_cols_men] = team_features_men[numeric_cols_men].replace([np.inf, -np.inf], np.nan)

numeric_cols_women = team_features_women.select_dtypes(include=[np.number]).columns
team_features_women[numeric_cols_women] = team_features_women[numeric_cols_women].replace([np.inf, -np.inf], np.nan)

In [42]:
print("Men shape:", team_features_men.shape)
print("Women shape:", team_features_women.shape)

Men shape: (8346, 46)
Women shape: (5965, 47)

In [43]:
print("Men columns:")
team_features_men.columns.tolist()

Men columns:

['Season',
 'TeamID',
 'Wins',
 'GamesPlayed',
 'AvgPointsFor',
 'AvgPointsAgainst',
 'AvgMarginScore',
 'MarginScoreStd',
 'AvgNumOT',
 'AvgFieldGoalsMade',
 'AvgFieldGoalsAttempted',
 'AvgFieldGoalsPct',
 'AvgThreePointsMade',
 'AvgThreePointsAttempted',
 'AvgThreePointsPct',
 'AvgFreeThrowsMade',
 'AvgFreeThrowsAttempted',
 'AvgFreeThrowPct',
 'AvgOffensiveRebounds',
 'AvgDefensiveRebounds',
 'AvgTotalRebounds',
 'AvgReboundPct',
 'AvgOffensiveReboundPct',
 'AvgDefensiveReboundPct',
 'AvgAssists',
 'AvgTurnovers',
 'AvgTurnoverPct',
 'AvgAssistTurnoverRto',
 'AvgSteals',
 'AvgBlocks',
 'AvgPersonalFouls',
 'AvgTurnoverMargin',
 'AvgReboundMargin',
 'AvgPossessions',
 'AvgOffEfficiency',
 'AvgDefEfficiency',
 'AvgNetRating',
 'AvgGameTotalPoints',
 'Losses',
 'WinPct',
 'LossPct',
 'ConfAbbrev',
 'Seed',
 'SeedNum',
 'HasTournamentSeed',
 'MasseyOrdinalRank']

In [44]:
print("Women columns:")
team_features_women.columns.tolist()

Women columns:

['Season',
 'TeamID',
 'Wins',
 'GamesPlayed',
 'AvgPointsFor',
 'AvgPointsAgainst',
 'AvgMarginScore',
 'MarginScoreStd',
 'AvgNumOT',
 'AvgFieldGoalsMade',
 'AvgFieldGoalsAttempted',
 'AvgFieldGoalsPct',
 'AvgThreePointsMade',
 'AvgThreePointsAttempted',
 'AvgThreePointsPct',
 'AvgFreeThrowsMade',
 'AvgFreeThrowsAttempted',
 'AvgFreeThrowPct',
 'AvgOffensiveRebounds',
 'AvgDefensiveRebounds',
 'AvgTotalRebounds',
 'AvgReboundPct',
 'AvgOffensiveReboundPct',
 'AvgDefensiveReboundPct',
 'AvgAssists',
 'AvgTurnovers',
 'AvgTurnoverPct',
 'AvgAssistTurnoverRto',
 'AvgSteals',
 'AvgBlocks',
 'AvgPersonalFouls',
 'AvgTurnoverMargin',
 'AvgReboundMargin',
 'AvgPossessions',
 'AvgOffEfficiency',
 'AvgDefEfficiency',
 'AvgNetRating',
 'AvgGameTotalPoints',
 'Losses',
 'WinPct',
 'LossPct',
 'ConfAbbrev',
 'Seed',
 'SeedNum',
 'HasTournamentSeed',
 'WMasseyRating',
 'WMasseySOS']

In [47]:
print("Men features seasons:", team_features_men["Season"].min(), team_features_men["Season"].max())
print("Women features seasons:", team_features_women["Season"].min(), team_features_women["Season"].max())

Men features seasons: 2003 2026
Women features seasons: 2010 2026

In [45]:
team_features_men.to_csv("../data/m_team_season_features.csv", index=False)
team_features_women.to_csv("../data/w_team_season_features.csv", index=False)