In [186]:
import pandas as pd
import numpy as np

### Load files

In [187]:
df_men = pd.read_csv("../data/MRegularSeasonDetailedResults.csv")
df_women = pd.read_csv("../data/WRegularSeasonDetailedResults.csv")

### Renaming files to increase readability

In [188]:
headers_rename = {

    # Winner team stats
    "WFGM":  "W_FieldGoalsMade",
    "WFGA":  "W_FieldGoalsAttempted",
    "WFGM3": "W_ThreePointsMade",
    "WFGA3": "W_ThreePointsAttempted",
    "WFTM":  "W_FreeThrowsMade",
    "WFTA":  "W_FreeThrowsAttempted",
    "WOR":   "W_OffensiveRebounds",
    "WDR":   "W_DefensiveRebounds",
    "WAst":  "W_Assists",
    "WTO":   "W_Turnovers",
    "WStl":  "W_Steals",
    "WBlk":  "W_Blocks",
    "WPF":   "W_PersonalFouls",

    # Losing team stats
    "LFGM":  "L_FieldGoalsMade",
    "LFGA":  "L_FieldGoalsAttempted",
    "LFGM3": "L_ThreePointsMade",
    "LFGA3": "L_ThreePointsAttempted",
    "LFTM":  "L_FreeThrowsMade",
    "LFTA":  "L_FreeThrowsAttempted",
    "LOR":   "L_OffensiveRebounds",
    "LDR":   "L_DefensiveRebounds",
    "LAst":  "L_Assists",
    "LTO":   "L_Turnovers",
    "LStl":  "L_Steals",
    "LBlk":  "L_Blocks",
    "LPF":   "L_PersonalFouls"
}

In [189]:
df_men = df_men.rename(columns = headers_rename)
df_men.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [190]:
df_women.rename(columns = headers_rename, inplace = True)
df_women.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
0,2010,11,3103,63,3237,49,H,0,23,54,...,13,6,10,11,27,11,23,7,6,19
1,2010,11,3104,73,3399,68,N,0,26,62,...,21,14,27,14,26,7,20,4,2,27
2,2010,11,3110,71,3224,59,A,0,29,62,...,14,19,23,17,23,8,15,6,0,15
3,2010,11,3111,63,3267,58,A,0,27,52,...,26,16,25,22,22,15,11,14,5,14
4,2010,11,3119,74,3447,70,H,1,30,74,...,17,11,21,21,32,12,14,4,2,14

In [191]:
df_men.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,W_ThreePointsMade,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
count,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,...,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000
mean,2014.622464,70.012674,1288.454653,76.080855,1283.434079,64.060827,0.068589,26.467457,55.858009,7.396669,...,20.285001,12.117614,17.766361,10.391236,21.578408,11.429664,13.801377,6.008748,2.873264,19.267049
std,6.784957,35.928210,105.480339,11.051733,104.986587,10.876749,0.304631,4.691850,7.447786,3.139463,...,6.108233,5.359096,7.084354,4.209703,4.516139,3.730345,4.383176,2.743815,2.016967,4.551296
min,2003.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000,10.000000,26.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.000000
25%,2009.000000,38.000000,1199.000000,68.000000,1192.000000,57.000000,0.000000,23.000000,51.000000,5.000000,...,16.000000,8.000000,13.000000,7.000000,18.000000,9.000000,11.000000,4.000000,1.000000,16.000000
50%,2015.000000,73.000000,1287.000000,76.000000,1282.000000,64.000000,0.000000,26.000000,56.000000,7.000000,...,20.000000,12.000000,17.000000,10.000000,21.000000,11.000000,13.000000,6.000000,3.000000,19.000000
75%,2020.000000,101.000000,1382.000000,83.000000,1374.000000,71.000000,0.000000,29.000000,61.000000,9.000000,...,24.000000,15.000000,22.000000,13.000000,25.000000,14.000000,17.000000,8.000000,4.000000,22.000000
max,2026.000000,132.000000,1481.000000,149.000000,1481.000000,144.000000,6.000000,57.000000,103.000000,26.000000,...,59.000000,48.000000,65.000000,36.000000,49.000000,31.000000,41.000000,22.000000,18.000000,45.000000

In [192]:
df_women.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,W_ThreePointsMade,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
count,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,...,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000
mean,2017.882416,68.827858,3285.435904,71.804163,3286.980492,57.258687,0.051412,25.885796,58.999474,6.316707,...,17.999836,10.502754,15.480580,11.209964,22.319935,10.929770,17.120484,7.112274,2.814631,18.174352
std,4.856439,36.312736,104.259376,11.567866,105.788375,10.945184,0.258102,4.991710,7.970657,3.131598,...,6.455423,4.930955,6.622443,4.635878,4.938710,3.803927,5.276003,3.191684,2.058725,4.558495
min,2010.000000,0.000000,3101.000000,30.000000,3101.000000,11.000000,0.000000,9.000000,30.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,3.000000
25%,2014.000000,34.000000,3196.000000,64.000000,3195.000000,50.000000,0.000000,22.000000,53.000000,4.000000,...,13.000000,7.000000,11.000000,8.000000,19.000000,8.000000,13.000000,5.000000,1.000000,15.000000
50%,2018.000000,72.000000,3283.000000,71.000000,3287.000000,57.000000,0.000000,25.000000,59.000000,6.000000,...,18.000000,10.000000,15.000000,11.000000,22.000000,11.000000,17.000000,7.000000,2.000000,18.000000
75%,2022.000000,100.000000,3377.000000,79.000000,3378.000000,64.000000,0.000000,29.000000,64.000000,8.000000,...,22.000000,14.000000,20.000000,14.000000,26.000000,13.000000,20.000000,9.000000,4.000000,21.000000
max,2026.000000,132.000000,3481.000000,140.000000,3481.000000,130.000000,5.000000,58.000000,113.000000,30.000000,...,80.000000,37.000000,52.000000,38.000000,53.000000,34.000000,49.000000,26.000000,21.000000,47.000000

#### Total Rebounds

In [193]:
df_men["W_TotalRebounds"] = df_men["W_OffensiveRebounds"] + df_men["W_DefensiveRebounds"]
df_men["L_TotalRebounds"] = df_men["L_OffensiveRebounds"] + df_men["L_DefensiveRebounds"]

#### Rebound % for winning and losing teams

In [194]:
df_men["W_ReboundPct"] = df_men["W_TotalRebounds"] / (df_men["W_TotalRebounds"] + df_men["L_TotalRebounds"])

In [195]:
df_men["L_ReboundPct"] = df_men["L_TotalRebounds"] / (df_men["W_TotalRebounds"] + df_men["L_TotalRebounds"])

#### Offensive Rebound %

In [196]:
df_men["W_OffensiveReboundPct"] = df_men["W_OffensiveRebounds"] / (df_men["W_OffensiveRebounds"] + df_men["L_DefensiveRebounds"])

In [197]:
df_men["L_OffensiveReboundPct"] = df_men["L_OffensiveRebounds"] / (df_men["L_OffensiveRebounds"] + df_men["W_DefensiveRebounds"])

#### Defensive Rebound %

In [198]:
df_men["W_DefensiveReboundPct"] = df_men["W_DefensiveRebounds"] / (df_men["W_DefensiveRebounds"] + df_men["L_OffensiveRebounds"])

In [199]:
df_men["L_DefensiveReboundPct"] = df_men["L_DefensiveRebounds"] / (df_men["L_DefensiveRebounds"] + df_men["W_OffensiveRebounds"])

In [200]:
df_men["W_TurnoverMargin"] = df_men["L_Turnovers"] - df_men["W_Turnovers"]
df_men["L_TurnoverMargin"] = df_men["W_Turnovers"] - df_men["L_Turnovers"]

In [201]:
df_men["W_ReboundMargin"] = df_men["W_TotalRebounds"] - df_men["L_TotalRebounds"]
df_men["L_ReboundMargin"] = df_men["L_TotalRebounds"] - df_men["W_TotalRebounds"]

### Let's separate the df between winners and losers stats

In [202]:
winner_df = pd.DataFrame({
    "Season": df_men["Season"],
    "DayNum": df_men["DayNum"],
    "NumOT": df_men["NumOT"],
    "TeamID": df_men["WTeamID"],
    "OpponentID": df_men["LTeamID"],
    "Win": 1,
    "PointsFor": df_men["WScore"],
    "PointsAgainst": df_men["LScore"],
    "FieldGoalsMade": df_men["W_FieldGoalsMade"],
    "FieldGoalsAttempted": df_men["W_FieldGoalsAttempted"],
    "ThreePointsMade": df_men["W_ThreePointsMade"],
    "ThreePointsAttempted": df_men["W_ThreePointsAttempted"],
    "FreeThrowsMade": df_men["W_FreeThrowsMade"],
    "FreeThrowsAttempted": df_men["W_FreeThrowsAttempted"],
    "OffensiveRebounds": df_men["W_OffensiveRebounds"],
    "DefensiveRebounds": df_men["W_DefensiveRebounds"],
    "Assists": df_men["W_Assists"],
    "Turnovers": df_men["W_Turnovers"],
    "Steals": df_men["W_Steals"],
    "Blocks": df_men["W_Blocks"],
    "PersonalFouls": df_men["W_PersonalFouls"],
    "TotalRebounds": df_men["W_TotalRebounds"],
    "ReboundPct": df_men["W_ReboundPct"],
    "OffensiveReboundPct": df_men["W_OffensiveReboundPct"],
    "DefensiveReboundPct": df_men["W_DefensiveReboundPct"],
    "OpponentTurnovers": df_men["L_Turnovers"],
    "OpponentTotalRebounds": df_men["L_TotalRebounds"],
    "TurnoverMargin": df_men["W_TurnoverMargin"],
    "ReboundMargin": df_men["W_ReboundMargin"],
})
winner_df.head(5)

,Season,DayNum,NumOT,TeamID,OpponentID,Win,PointsFor,PointsAgainst,FieldGoalsMade,FieldGoalsAttempted,...,Blocks,PersonalFouls,TotalRebounds,ReboundPct,OffensiveReboundPct,DefensiveReboundPct,OpponentTurnovers,OpponentTotalRebounds,TurnoverMargin,ReboundMargin
0,2003,10,0,1104,1328,1,68,62,27,58,...,1,22,38,0.542857,0.388889,0.705882,18,32,-5,6
1,2003,10,0,1272,1393,1,70,63,26,62,...,4,18,43,0.488636,0.375000,0.583333,12,45,-1,-2
2,2003,11,0,1266,1437,1,73,61,24,58,...,2,25,43,0.447917,0.435897,0.456140,12,53,2,-10
3,2003,11,0,1296,1457,1,56,50,18,38,...,2,18,25,0.403226,0.230769,0.527778,19,37,7,-12
4,2003,11,0,1400,1208,1,77,71,30,61,...,4,20,39,0.520000,0.531250,0.511628,10,36,-4,3

In [203]:
loser_df = pd.DataFrame({
    "Season": df_men["Season"],
    "DayNum": df_men["DayNum"],
    "NumOT": df_men["NumOT"],
    "TeamID": df_men["LTeamID"],
    "OpponentID": df_men["WTeamID"],
    "Win": 0,
    "PointsFor": df_men["LScore"],
    "PointsAgainst": df_men["WScore"],
    "FieldGoalsMade": df_men["L_FieldGoalsMade"],
    "FieldGoalsAttempted": df_men["L_FieldGoalsAttempted"],
    "ThreePointsMade": df_men["L_ThreePointsMade"],
    "ThreePointsAttempted": df_men["L_ThreePointsAttempted"],
    "FreeThrowsMade": df_men["L_FreeThrowsMade"],
    "FreeThrowsAttempted": df_men["L_FreeThrowsAttempted"],
    "OffensiveRebounds": df_men["L_OffensiveRebounds"],
    "DefensiveRebounds": df_men["L_DefensiveRebounds"],
    "Assists": df_men["L_Assists"],
    "Turnovers": df_men["L_Turnovers"],
    "Steals": df_men["L_Steals"],
    "Blocks": df_men["L_Blocks"],
    "PersonalFouls": df_men["L_PersonalFouls"],
    "TotalRebounds": df_men["L_TotalRebounds"],
    "ReboundPct": df_men["L_ReboundPct"],
    "OffensiveReboundPct": df_men["L_OffensiveReboundPct"],
    "DefensiveReboundPct": df_men["L_DefensiveReboundPct"],
    "OpponentTurnovers": df_men["W_Turnovers"],
    "OpponentTotalRebounds": df_men["W_TotalRebounds"],
    "TurnoverMargin": df_men["L_TurnoverMargin"],
    "ReboundMargin": df_men["L_ReboundMargin"],
})
loser_df.head(5)

,Season,DayNum,NumOT,TeamID,OpponentID,Win,PointsFor,PointsAgainst,FieldGoalsMade,FieldGoalsAttempted,...,Blocks,PersonalFouls,TotalRebounds,ReboundPct,OffensiveReboundPct,DefensiveReboundPct,OpponentTurnovers,OpponentTotalRebounds,TurnoverMargin,ReboundMargin
0,2003,10,0,1328,1104,0,62,68,22,53,...,2,20,32,0.457143,0.294118,0.611111,23,38,5,-6
1,2003,10,0,1393,1272,0,63,70,24,67,...,6,16,45,0.511364,0.416667,0.625000,13,43,1,2
2,2003,11,0,1437,1266,0,61,73,22,73,...,5,23,53,0.552083,0.543860,0.564103,10,43,-2,10
3,2003,11,0,1457,1296,0,50,56,18,49,...,3,23,37,0.596774,0.472222,0.769231,12,25,-7,12
4,2003,11,0,1208,1400,0,71,77,24,62,...,1,14,36,0.480000,0.488372,0.468750,14,39,4,-3

According to previous winners, score marging is a good and strong indicator on team's potential to win. It's calculated by the difference in points scored between a team and its oppnents over a season.

In [204]:
winner_df["MarginScore"] = winner_df["PointsFor"] - winner_df["PointsAgainst"]
loser_df["MarginScore"] = loser_df["PointsFor"] - loser_df["PointsAgainst"]

In [205]:
winner_df["MarginScore"].head(5)

0     6
1     7
2    12
3     6
4     6
Name: MarginScore, dtype: int64

In [206]:
loser_df["MarginScore"].head(5)

0    -6
1    -7
2   -12
3    -6
4    -6
Name: MarginScore, dtype: int64

### Aggreagtions to check possible correlation between these numbers and win or loss

In [207]:
winner_df_stats = winner_df.groupby([
    "Season",
    "TeamID",
], as_index=False).agg({
    "Win": "sum",
    "PointsFor":"mean",
    "PointsAgainst":"mean",
    "MarginScore":"mean",
    "FieldGoalsMade":"mean",
    "FieldGoalsAttempted":"mean",
    "ThreePointsMade":"mean",
    "ThreePointsAttempted":"mean",
    "FreeThrowsMade":"mean",
    "FreeThrowsAttempted":"mean",
    "OffensiveRebounds":"mean",
    "DefensiveRebounds":"mean",
    "Assists":"mean",
    "Turnovers":"mean",
    "Steals":"mean",
    "Blocks":"mean",
    "PersonalFouls":"mean",
    "TotalRebounds": "mean",
    "ReboundPct": "mean",
    "OffensiveReboundPct": "mean",
    "DefensiveReboundPct": "mean",
    "TurnoverMargin": "mean",
    "ReboundMargin": "mean",
})
winner_df_stats.head(5)

,Season,TeamID,Win,PointsFor,PointsAgainst,MarginScore,FieldGoalsMade,FieldGoalsAttempted,ThreePointsMade,ThreePointsAttempted,...,Turnovers,Steals,Blocks,PersonalFouls,TotalRebounds,ReboundPct,OffensiveReboundPct,DefensiveReboundPct,TurnoverMargin,ReboundMargin
0,2003,1102,12,68.750000,53.166667,15.583333,22.583333,40.000000,10.000000,21.583333,...,11.083333,7.333333,2.833333,16.083333,23.166667,0.443378,0.172188,0.636526,3.083333,-5.416667
1,2003,1103,13,87.769231,78.384615,9.384615,30.000000,55.384615,5.461538,14.384615,...,12.538462,7.307692,1.846154,20.461538,30.846154,0.481575,0.318510,0.620109,3.461538,-2.615385
2,2003,1104,17,74.705882,61.529412,13.176471,25.823529,58.352941,7.058824,20.823529,...,13.058824,7.235294,4.176471,16.470588,39.941176,0.537399,0.367049,0.703299,2.058824,5.823529
3,2003,1105,7,79.428571,66.428571,13.000000,25.571429,61.857143,9.142857,22.428571,...,18.000000,11.285714,2.000000,19.428571,40.428571,0.523805,0.383144,0.667596,4.000000,3.714286
4,2003,1106,13,68.307692,57.923077,10.384615,24.769231,53.846154,5.846154,15.923077,...,17.692308,9.384615,3.769231,18.384615,40.769231,0.563930,0.378952,0.714061,-1.769231,9.692308

In [208]:
loser_df_stats = loser_df.groupby([
    "Season",
    "TeamID",
], as_index=False).agg({
    "Win": "sum",
    "PointsFor":"mean",
    "PointsAgainst":"mean",
    "MarginScore":"mean",
    "FieldGoalsMade":"mean",
    "FieldGoalsAttempted":"mean",
    "ThreePointsMade":"mean",
    "ThreePointsAttempted":"mean",
    "FreeThrowsMade":"mean",
    "FreeThrowsAttempted":"mean",
    "OffensiveRebounds":"mean",
    "DefensiveRebounds":"mean",
    "Assists":"mean",
    "Turnovers":"mean",
    "Steals":"mean",
    "Blocks":"mean",
    "PersonalFouls":"mean",
    "TotalRebounds": "mean",
    "ReboundPct": "mean",
    "OffensiveReboundPct": "mean",
    "DefensiveReboundPct": "mean",
    "TurnoverMargin": "mean",
    "ReboundMargin": "mean",
})
loser_df_stats.rename(columns={"Win": "Losses"}, inplace=True)
loser_df_stats.head(5)

,Season,TeamID,Losses,PointsFor,PointsAgainst,MarginScore,FieldGoalsMade,FieldGoalsAttempted,ThreePointsMade,ThreePointsAttempted,...,Turnovers,Steals,Blocks,PersonalFouls,TotalRebounds,ReboundPct,OffensiveReboundPct,DefensiveReboundPct,TurnoverMargin,ReboundMargin
0,2003,1102,0,48.625000,59.875000,-11.250000,16.562500,39.625000,6.187500,20.250000,...,11.687500,4.937500,1.000000,20.750000,19.375000,0.385005,0.165271,0.625778,0.375000,-11.250000
1,2003,1103,0,70.428571,77.928571,-7.500000,24.500000,56.285714,5.428571,17.642857,...,12.714286,7.214286,2.785714,19.285714,28.642857,0.455436,0.294003,0.633394,2.000000,-6.000000
2,2003,1104,0,60.909091,70.363636,-9.454545,21.272727,55.363636,5.272727,18.363636,...,13.636364,5.636364,3.181818,20.454545,33.727273,0.509631,0.377756,0.661550,-1.727273,1.090909
3,2003,1105,0,68.947368,80.421053,-11.473684,23.947368,61.526316,7.000000,20.157895,...,18.894737,8.578947,2.105263,20.526316,35.210526,0.462816,0.317489,0.631796,-1.263158,-5.421053
4,2003,1106,0,59.533333,68.800000,-9.266667,22.266667,56.533333,6.333333,19.133333,...,16.466667,7.466667,2.600000,18.000000,32.133333,0.470736,0.323938,0.649253,-2.133333,-3.800000

In [209]:
winner_df_stats.to_csv("../data/m_winner_df_stats.csv", index=False)
loser_df_stats.to_csv("../data/m_loser_df_stats.csv", index=False)

# @Dan and @Jason working on spotting possible correlations between win and everything else

# TODO:
- What's the correlation between win vs teams? - Using Orange Data Mining for this

# TODO:
- Can we add conferences to our main df? Then we can analyze how the conference affects the winning/losing team

- `MConferenceTourneyGames` has information such as conf abbreviation, wteam, lteam
- `Conferences` has the abbreviation and the actual name
- `MTeamConferences` has the team, the season, and its conference

Can we split the df into winners and losers teams and analyze them? Or maybe we can transform the df into long format

### TODO: We need to add conference information, as teams playing away may be in disadvantage

I'm still confused about seeds information and how to properly use them

### TODO:
- Recommended to me to find the FieldGoal percentage
- Free Throws percentage
- Turnover percentage
- Total rebounds
- Assists turnover ratio
- Rebound percentage

- For th TODOS above, we are going back to the initial dfs

In [210]:
games_men = pd.concat([winner_df, loser_df], ignore_index=True)
games_men.head()

,Season,DayNum,NumOT,TeamID,OpponentID,Win,PointsFor,PointsAgainst,FieldGoalsMade,FieldGoalsAttempted,...,PersonalFouls,TotalRebounds,ReboundPct,OffensiveReboundPct,DefensiveReboundPct,OpponentTurnovers,OpponentTotalRebounds,TurnoverMargin,ReboundMargin,MarginScore
0,2003,10,0,1104,1328,1,68,62,27,58,...,22,38,0.542857,0.388889,0.705882,18,32,-5,6,6
1,2003,10,0,1272,1393,1,70,63,26,62,...,18,43,0.488636,0.375000,0.583333,12,45,-1,-2,7
2,2003,11,0,1266,1437,1,73,61,24,58,...,25,43,0.447917,0.435897,0.456140,12,53,2,-10,12
3,2003,11,0,1296,1457,1,56,50,18,38,...,18,25,0.403226,0.230769,0.527778,19,37,7,-12,6
4,2003,11,0,1400,1208,1,77,71,30,61,...,20,39,0.520000,0.531250,0.511628,10,36,-4,3,6

# FieldGoals Percentage @Gabe
`FG%=FGM / FGA`

In [211]:
games_men["FieldGoalsPct"] = games_men["FieldGoalsMade"] / games_men["FieldGoalsAttempted"]
games_men["FieldGoalsPct"].head(5)

0    0.465517
1    0.419355
2    0.413793
3    0.473684
4    0.491803
Name: FieldGoalsPct, dtype: float64

# 3 Points Percentage @Gabe
`3P% = 3PM/3PA`

In [212]:
games_men["ThreePointsMadePct"] = games_men["ThreePointsMade"] / games_men["ThreePointsAttempted"]
games_men["ThreePointsMadePct"]

0         0.214286
1         0.400000
2         0.444444
3         0.333333
4         0.428571
            ...
245545    0.300000
245546    0.291667
245547    0.263158
245548    0.185185
245549    0.411765
Name: ThreePointsMadePct, Length: 245550, dtype: float64

# Free throws percentage @Gabe
`FT% = FTM / FTA`

In [213]:
games_men["FreeThrowPct"] = games_men["FreeThrowsMade"] / games_men["FreeThrowsAttempted"]
games_men["FreeThrowPct"].head(5)

0    0.611111
1    0.526316
2    0.586207
3    0.548387
4    0.846154
Name: FreeThrowPct, dtype: float64

# Turnover percentage @ Gabe
`TO% = TO / FGA + 0.44 * FTA + TO`

In [214]:
games_men["TurnoverPct"] = games_men["Turnovers"] / (games_men["FieldGoalsAttempted"] + 0.44 * games_men["FreeThrowsAttempted"] + games_men["Turnovers"])
games_men["TurnoverPct"].head(5)

0    0.258659
1    0.155950
2    0.123824
3    0.188561
4    0.173439
Name: TurnoverPct, dtype: float64

# Total rebound @Dan
`TRB = OR + DR`
- Calculated before

# Rebound percentage @Dan
`REB% = REB / REB + oppREB`
- Done before merging!

# Assist turnover ratio @Gabe
` AST/TO = AST / TO`

In [215]:
games_men["AssistTurnoverRto"] = games_men["Assists"] / games_men["Turnovers"]
games_men["AssistTurnoverRto"].head(5)

0    0.565217
1    1.230769
2    1.500000
3    0.916667
4    0.857143
Name: AssistTurnoverRto, dtype: float64

# Points per game @Gabe

In [216]:
games_men["GameTotalPoints"] = games_men["PointsAgainst"] + games_men["PointsFor"]
games_men["GameTotalPoints"].head(5)

0    130
1    133
2    134
3    106
4    148
Name: GameTotalPoints, dtype: int64

# Offensive rebound percentage @Dan
` or% = offReb / offReb + oppDefReb`
- Done before merging

# Defensive rebound % @Dan
`DR% = defReb / defReb + oppOffReb`
- Done before merging

# Possessions @Hafsa
`Poss = FGA - OR + TO + 0.44 * FTA`

In [217]:
games_men["Possessions"] = (
    (games_men["FieldGoalsAttempted"]- games_men["OffensiveRebounds"] + games_men["Turnovers"] + 0.44 * games_men["FreeThrowsAttempted"]
     ))

games_men["Possessions"].head()

0    74.92
1    68.36
2    63.76
3    57.64
4    63.72
Name: Possessions, dtype: float64

# Offensive efficiency @Hafsa
`offRating = Points / Possesion`

In [218]:
games_men["OffEfficiency"]= games_men["PointsFor"] / games_men["Possessions"]
games_men["OffEfficiency"].head()

0    0.907635
1    1.023991
2    1.144918
3    0.971548
4    1.208412
Name: OffEfficiency, dtype: float64

# Defensive efficiency @Hafsa
defRating = OppPoints / Possessions

In [219]:
games_men["DefEfficiency"]= games_men["PointsAgainst"] / games_men["Possessions"]
games_men["DefEfficiency"].head()

0    0.827549
1    0.921592
2    0.956713
3    0.867453
4    1.114250
Name: DefEfficiency, dtype: float64

# Net efficiency @ Hafsa
`NetRating = offRating - defRating`

In [220]:
games_men["NetRating"] = games_men["OffEfficiency"] - games_men["DefEfficiency"]
games_men["NetRating"].head()

0    0.080085
1    0.102399
2    0.188206
3    0.104094
4    0.094162
Name: NetRating, dtype: float64

# Team win percentage @Gabe
`wins = wins / games`

In [222]:
games_men["GamesPlayed"] = games_men.groupby(["Season", "TeamID"])["Win"].transform("count")

In [223]:
games_men["Wins"] = games_men.groupby(["Season", "TeamID"])["Win"].transform("sum")
games_men["WinPct"] = games_men["Wins"] / games_men["GamesPlayed"]
games_men[["Season","TeamID","Wins","GamesPlayed","WinPct"]].head()

   Season  TeamID  Wins  GamesPlayed    WinPct
0    2003    1104    17           28  0.607143
1    2003    1272    23           29  0.793103
2    2003    1266    23           28  0.821429
3    2003    1296    17           31  0.548387
4    2003    1400    22           28  0.785714

In [224]:
games_men["Losses"] = games_men["GamesPlayed"] - games_men["Wins"]
games_men["LossPct"] = games_men["Losses"] / games_men["GamesPlayed"]
games_men[["Season","TeamID","Losses","GamesPlayed","LossPct"]].head()

   Season  TeamID  Losses  GamesPlayed   LossPct
0    2003    1104      11           28  0.392857
1    2003    1272       6           29  0.206897
2    2003    1266       5           28  0.178571
3    2003    1296      14           31  0.451613
4    2003    1400       6           28  0.214286

# Strength of schedule @Jason
- Gonna investigate how to do this -> Jason worked on this
- Check massey_methods

# Games played @Gabe

In [225]:
games_men["GamesPlayed"] = games_men.groupby(["Season", "TeamID"])["Win"].transform("count")

# Add conference information @Anyone???
- So we can figure out which games were away and which ones were home

# Seed  @Anyone???
- Create a seed difference