In [35]:
import pandas as pd
import numpy as np

### Load files

In [36]:
df_men = pd.read_csv("../data/MRegularSeasonDetailedResults.csv")
df_women = pd.read_csv("../data/WRegularSeasonDetailedResults.csv")

In [37]:
df_idk_men = pd.read_csv("../data/MNCAATourneyDetailedResults.csv")
df_idk_women = pd.read_csv("../data/WNCAATourneyDetailedResults.csv")

### Renaming files to increase readability

In [38]:
headers_rename = {

    # Winner team stats
    "WFGM":  "W_FieldGoalsMade",
    "WFGA":  "W_FieldGoalsAttempted",
    "WFGM3": "W_ThreePointsMade",
    "WFGA3": "W_ThreePointsAttempted",
    "WFTM":  "W_FreeThrowsMade",
    "WFTA":  "W_FreeThrowsAttempted",
    "WOR":   "W_OffensiveRebounds",
    "WDR":   "W_DefensiveRebounds",
    "WAst":  "W_Assists",
    "WTO":   "W_Turnovers",
    "WStl":  "W_Steals",
    "WBlk":  "W_Blocks",
    "WPF":   "W_PersonalFouls",

    # Losing team stats
    "LFGM":  "L_FieldGoalsMade",
    "LFGA":  "L_FieldGoalsAttempted",
    "LFGM3": "L_ThreePointsMade",
    "LFGA3": "L_ThreePointsAttempted",
    "LFTM":  "L_FreeThrowsMade",
    "LFTA":  "L_FreeThrowsAttempted",
    "LOR":   "L_OffensiveRebounds",
    "LDR":   "L_DefensiveRebounds",
    "LAst":  "L_Assists",
    "LTO":   "L_Turnovers",
    "LStl":  "L_Steals",
    "LBlk":  "L_Blocks",
    "LPF":   "L_PersonalFouls"
}

In [43]:
df_men = df_men.rename(columns = headers_rename)
df_men.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFieldGoals,WFieldGoals,...,LThreePointers,LFreeThrowsMade,LFreeThrowAttempt,LOffensiveRebounds,LDefensiveRebounds,LaAssists,LTurnoversCommited,LSteals,LBlocks,LPersonalFouls
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122770,2026,93,1457,80,1347,78,A,0,29,60,...,30,13,17,12,26,12,12,7,0,18
122771,2026,93,1459,81,1440,67,A,0,26,57,...,24,14,19,6,26,13,7,4,2,16
122772,2026,93,1464,90,1236,61,A,0,35,53,...,19,8,11,3,15,6,9,6,1,12
122773,2026,93,1472,77,1355,62,A,0,27,56,...,27,11,15,7,26,14,9,2,1,15
122774,2026,93,1477,74,1322,68,A,0,27,52,...,17,7,14,4,21,15,8,7,0,13

In [44]:
df_women.rename(columns = headers_rename, inplace = True)
df_women.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFieldGoals,WFieldGoals,...,LThreePointers,LFreeThrowsMade,LFreeThrowAttempt,LOffensiveRebounds,LDefensiveRebounds,LaAssists,LTurnoversCommited,LSteals,LBlocks,LPersonalFouls
0,2010,11,3103,63,3237,49,H,0,23,54,...,13,6,10,11,27,11,23,7,6,19
1,2010,11,3104,73,3399,68,N,0,26,62,...,21,14,27,14,26,7,20,4,2,27
2,2010,11,3110,71,3224,59,A,0,29,62,...,14,19,23,17,23,8,15,6,0,15
3,2010,11,3111,63,3267,58,A,0,27,52,...,26,16,25,22,22,15,11,14,5,14
4,2010,11,3119,74,3447,70,H,1,30,74,...,17,11,21,21,32,12,14,4,2,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85500,2026,93,3421,60,3149,48,A,0,20,56,...,21,15,21,4,22,8,7,4,5,22
85501,2026,93,3428,67,3416,57,A,0,24,57,...,14,12,16,11,22,10,15,6,7,11
85502,2026,93,3437,67,3139,57,A,0,27,64,...,15,7,10,5,22,11,16,5,2,10
85503,2026,93,3452,61,3160,55,A,0,24,58,...,9,15,19,9,27,9,17,8,3,14
85504,2026,93,3466,55,3122,50,H,0,19,45,...,21,14,20,12,21,7,14,5,1,22

In [39]:
df_men.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,WFGM,WFGA,WFGM3,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
count,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,...,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000
mean,2014.622464,70.012674,1288.454653,76.080855,1283.434079,64.060827,0.068589,26.467457,55.858009,7.396669,...,20.285001,12.117614,17.766361,10.391236,21.578408,11.429664,13.801377,6.008748,2.873264,19.267049
std,6.784957,35.928210,105.480339,11.051733,104.986587,10.876749,0.304631,4.691850,7.447786,3.139463,...,6.108233,5.359096,7.084354,4.209703,4.516139,3.730345,4.383176,2.743815,2.016967,4.551296
min,2003.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000,10.000000,26.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.000000
25%,2009.000000,38.000000,1199.000000,68.000000,1192.000000,57.000000,0.000000,23.000000,51.000000,5.000000,...,16.000000,8.000000,13.000000,7.000000,18.000000,9.000000,11.000000,4.000000,1.000000,16.000000
50%,2015.000000,73.000000,1287.000000,76.000000,1282.000000,64.000000,0.000000,26.000000,56.000000,7.000000,...,20.000000,12.000000,17.000000,10.000000,21.000000,11.000000,13.000000,6.000000,3.000000,19.000000
75%,2020.000000,101.000000,1382.000000,83.000000,1374.000000,71.000000,0.000000,29.000000,61.000000,9.000000,...,24.000000,15.000000,22.000000,13.000000,25.000000,14.000000,17.000000,8.000000,4.000000,22.000000
max,2026.000000,132.000000,1481.000000,149.000000,1481.000000,144.000000,6.000000,57.000000,103.000000,26.000000,...,59.000000,48.000000,65.000000,36.000000,49.000000,31.000000,41.000000,22.000000,18.000000,45.000000

In [40]:
df_women.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,WFGM,WFGA,WFGM3,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
count,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,...,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000
mean,2017.882416,68.827858,3285.435904,71.804163,3286.980492,57.258687,0.051412,25.885796,58.999474,6.316707,...,17.999836,10.502754,15.480580,11.209964,22.319935,10.929770,17.120484,7.112274,2.814631,18.174352
std,4.856439,36.312736,104.259376,11.567866,105.788375,10.945184,0.258102,4.991710,7.970657,3.131598,...,6.455423,4.930955,6.622443,4.635878,4.938710,3.803927,5.276003,3.191684,2.058725,4.558495
min,2010.000000,0.000000,3101.000000,30.000000,3101.000000,11.000000,0.000000,9.000000,30.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,3.000000
25%,2014.000000,34.000000,3196.000000,64.000000,3195.000000,50.000000,0.000000,22.000000,53.000000,4.000000,...,13.000000,7.000000,11.000000,8.000000,19.000000,8.000000,13.000000,5.000000,1.000000,15.000000
50%,2018.000000,72.000000,3283.000000,71.000000,3287.000000,57.000000,0.000000,25.000000,59.000000,6.000000,...,18.000000,10.000000,15.000000,11.000000,22.000000,11.000000,17.000000,7.000000,2.000000,18.000000
75%,2022.000000,100.000000,3377.000000,79.000000,3378.000000,64.000000,0.000000,29.000000,64.000000,8.000000,...,22.000000,14.000000,20.000000,14.000000,26.000000,13.000000,20.000000,9.000000,4.000000,21.000000
max,2026.000000,132.000000,3481.000000,140.000000,3481.000000,130.000000,5.000000,58.000000,113.000000,30.000000,...,80.000000,37.000000,52.000000,38.000000,53.000000,34.000000,49.000000,26.000000,21.000000,47.000000

## Set the df in long format so we have 2 rows per game

TODO - @Dan

1. Do they have the same seasons in both df?
2. Is DayNum the same in both df?
3. Tip: Try to find the same game in both datasets and see if they match. Would we gain anything new by merging them?

TODO:
1. Can we add conferences to our main df? Then we can analyze how the conference affects the winning/losing team
2. Can we also add the team names to our df?

Can we split the df into winners and losers teams and analyze them? Or maybe we can transform the df into long format

### Calculate total points per game

We could add some plots based on some metrics, like 3 points shots, blocks, steals or whatever other metrics are important for basktball, maybe @Dan can help with that?

### Calculate the margin differenc of points per game

### TODO: We need to add conference information, as teams playing away may be in disadvantage

### Can we create a Team statistics? Like team total wins, average points scored, etc - Maybe per season?

I'm still confused about seeds information and how to properly use them