In [54]:
import pandas as pd
import numpy as np

### Load files

In [55]:
df_men = pd.read_csv("../data/MRegularSeasonDetailedResults.csv")
df_women = pd.read_csv("../data/WRegularSeasonDetailedResults.csv")

### Renaming files to increase readability

In [56]:
headers_rename = {

    # Winner team stats
    "WFGM":  "W_FieldGoalsMade",
    "WFGA":  "W_FieldGoalsAttempted",
    "WFGM3": "W_ThreePointsMade",
    "WFGA3": "W_ThreePointsAttempted",
    "WFTM":  "W_FreeThrowsMade",
    "WFTA":  "W_FreeThrowsAttempted",
    "WOR":   "W_OffensiveRebounds",
    "WDR":   "W_DefensiveRebounds",
    "WAst":  "W_Assists",
    "WTO":   "W_Turnovers",
    "WStl":  "W_Steals",
    "WBlk":  "W_Blocks",
    "WPF":   "W_PersonalFouls",

    # Losing team stats
    "LFGM":  "L_FieldGoalsMade",
    "LFGA":  "L_FieldGoalsAttempted",
    "LFGM3": "L_ThreePointsMade",
    "LFGA3": "L_ThreePointsAttempted",
    "LFTM":  "L_FreeThrowsMade",
    "LFTA":  "L_FreeThrowsAttempted",
    "LOR":   "L_OffensiveRebounds",
    "LDR":   "L_DefensiveRebounds",
    "LAst":  "L_Assists",
    "LTO":   "L_Turnovers",
    "LStl":  "L_Steals",
    "LBlk":  "L_Blocks",
    "LPF":   "L_PersonalFouls"
}

In [57]:
df_men = df_men.rename(columns = headers_rename)
df_men.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [58]:
df_women.rename(columns = headers_rename, inplace = True)
df_women.head(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
0,2010,11,3103,63,3237,49,H,0,23,54,...,13,6,10,11,27,11,23,7,6,19
1,2010,11,3104,73,3399,68,N,0,26,62,...,21,14,27,14,26,7,20,4,2,27
2,2010,11,3110,71,3224,59,A,0,29,62,...,14,19,23,17,23,8,15,6,0,15
3,2010,11,3111,63,3267,58,A,0,27,52,...,26,16,25,22,22,15,11,14,5,14
4,2010,11,3119,74,3447,70,H,1,30,74,...,17,11,21,21,32,12,14,4,2,14

In [59]:
df_men.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,W_ThreePointsMade,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
count,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,...,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000,122775.000000
mean,2014.622464,70.012674,1288.454653,76.080855,1283.434079,64.060827,0.068589,26.467457,55.858009,7.396669,...,20.285001,12.117614,17.766361,10.391236,21.578408,11.429664,13.801377,6.008748,2.873264,19.267049
std,6.784957,35.928210,105.480339,11.051733,104.986587,10.876749,0.304631,4.691850,7.447786,3.139463,...,6.108233,5.359096,7.084354,4.209703,4.516139,3.730345,4.383176,2.743815,2.016967,4.551296
min,2003.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000,10.000000,26.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.000000
25%,2009.000000,38.000000,1199.000000,68.000000,1192.000000,57.000000,0.000000,23.000000,51.000000,5.000000,...,16.000000,8.000000,13.000000,7.000000,18.000000,9.000000,11.000000,4.000000,1.000000,16.000000
50%,2015.000000,73.000000,1287.000000,76.000000,1282.000000,64.000000,0.000000,26.000000,56.000000,7.000000,...,20.000000,12.000000,17.000000,10.000000,21.000000,11.000000,13.000000,6.000000,3.000000,19.000000
75%,2020.000000,101.000000,1382.000000,83.000000,1374.000000,71.000000,0.000000,29.000000,61.000000,9.000000,...,24.000000,15.000000,22.000000,13.000000,25.000000,14.000000,17.000000,8.000000,4.000000,22.000000
max,2026.000000,132.000000,1481.000000,149.000000,1481.000000,144.000000,6.000000,57.000000,103.000000,26.000000,...,59.000000,48.000000,65.000000,36.000000,49.000000,31.000000,41.000000,22.000000,18.000000,45.000000

In [60]:
df_women.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,W_FieldGoalsMade,W_FieldGoalsAttempted,W_ThreePointsMade,...,L_ThreePointsAttempted,L_FreeThrowsMade,L_FreeThrowsAttempted,L_OffensiveRebounds,L_DefensiveRebounds,L_Assists,L_Turnovers,L_Steals,L_Blocks,L_PersonalFouls
count,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,...,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000,85505.000000
mean,2017.882416,68.827858,3285.435904,71.804163,3286.980492,57.258687,0.051412,25.885796,58.999474,6.316707,...,17.999836,10.502754,15.480580,11.209964,22.319935,10.929770,17.120484,7.112274,2.814631,18.174352
std,4.856439,36.312736,104.259376,11.567866,105.788375,10.945184,0.258102,4.991710,7.970657,3.131598,...,6.455423,4.930955,6.622443,4.635878,4.938710,3.803927,5.276003,3.191684,2.058725,4.558495
min,2010.000000,0.000000,3101.000000,30.000000,3101.000000,11.000000,0.000000,9.000000,30.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,3.000000
25%,2014.000000,34.000000,3196.000000,64.000000,3195.000000,50.000000,0.000000,22.000000,53.000000,4.000000,...,13.000000,7.000000,11.000000,8.000000,19.000000,8.000000,13.000000,5.000000,1.000000,15.000000
50%,2018.000000,72.000000,3283.000000,71.000000,3287.000000,57.000000,0.000000,25.000000,59.000000,6.000000,...,18.000000,10.000000,15.000000,11.000000,22.000000,11.000000,17.000000,7.000000,2.000000,18.000000
75%,2022.000000,100.000000,3377.000000,79.000000,3378.000000,64.000000,0.000000,29.000000,64.000000,8.000000,...,22.000000,14.000000,20.000000,14.000000,26.000000,13.000000,20.000000,9.000000,4.000000,21.000000
max,2026.000000,132.000000,3481.000000,140.000000,3481.000000,130.000000,5.000000,58.000000,113.000000,30.000000,...,80.000000,37.000000,52.000000,38.000000,53.000000,34.000000,49.000000,26.000000,21.000000,47.000000

#### Total Rebounds

In [61]:
df_men["W_TotalRebounds"] = df_men["W_OffensiveRebounds"] + df_men["W_DefensiveRebounds"]
df_men["L_TotalRebounds"] = df_men["L_OffensiveRebounds"] + df_men["L_DefensiveRebounds"]

#### Rebound % for winning and losing teams

In [62]:
df_men["W_ReboundPct"] = df_men["W_TotalRebounds"] / (df_men["W_TotalRebounds"] + df_men["L_TotalRebounds"])

In [63]:
df_men["L_ReboundPct"] = df_men["L_TotalRebounds"] / (df_men["W_TotalRebounds"] + df_men["L_TotalRebounds"])

#### Offensive Rebound %

In [64]:
df_men["W_OffensiveReboundPct"] = df_men["W_OffensiveRebounds"] / (df_men["W_OffensiveRebounds"] + df_men["L_DefensiveRebounds"])

In [65]:
df_men["L_OffensiveReboundPct"] = df_men["L_OffensiveRebounds"] / (df_men["L_OffensiveRebounds"] + df_men["W_DefensiveRebounds"])

#### Defensive Rebound %

In [66]:
df_men["W_DefensiveReboundsPct"] = df_men["W_DefensiveRebounds"] / (df_men["W_DefensiveRebounds"] + df_men["L_OffensiveRebounds"])

In [67]:
df_men["L_DefensiveReboundsPct"] = df_men["L_DefensiveRebounds"] / (df_men["L_DefensiveRebounds"] + df_men["W_OffensiveRebounds"])

### Let's separate the df between winners and losers stats

In [68]:
winner_df = pd.DataFrame({
    "Season": df_men["Season"],
    "DayNum": df_men["DayNum"],
    "NumOT": df_men["NumOT"],
    "TeamID": df_men["WTeamID"],
    "OpponentID": df_men["LTeamID"],
    "Win": 1,
    "PointsFor": df_men["WScore"],
    "PointsAgainst": df_men["LScore"],
    "FieldGoalsMade": df_men["W_FieldGoalsMade"],
    "FieldGoalsAttempted": df_men["W_FieldGoalsAttempted"],
    "ThreePointsMade": df_men["W_ThreePointsMade"],
    "ThreePointsAttempted": df_men["W_ThreePointsAttempted"],
    "FreeThrowsMade": df_men["W_FreeThrowsMade"],
    "FreeThrowsAttempted": df_men["W_FreeThrowsAttempted"],
    "OffensiveRebounds": df_men["W_OffensiveRebounds"],
    "DefensiveRebounds": df_men["W_DefensiveRebounds"],
    "Assists": df_men["W_Assists"],
    "Turnovers": df_men["W_Turnovers"],
    "Steals": df_men["W_Steals"],
    "Blocks": df_men["W_Blocks"],
    "PersonalFouls": df_men["W_PersonalFouls"],
    "W_TotalRebounds": df_men["W_TotalRebounds"],
    "W_ReboundPct": df_men["W_ReboundPct"],
    "W_OffensiveReboundPct": df_men["W_OffensiveReboundPct"],
    "W_DefensiveReboundPct": df_men["W_DefensiveReboundPct"],
})
winner_df.head(5)

KeyError: 'W_DefensiveReboundPct'

In [ ]:
loser_df = pd.DataFrame({
    "Season": df_men["Season"],
    "DayNum": df_men["DayNum"],
    "NumOT": df_men["NumOT"],
    "TeamID": df_men["LTeamID"],
    "OpponentID": df_men["WTeamID"],
    "Win": 0,
    "PointsFor": df_men["LScore"],
    "PointsAgainst": df_men["WScore"],
    "FieldGoalsMade": df_men["L_FieldGoalsMade"],
    "FieldGoalsAttempted": df_men["L_FieldGoalsAttempted"],
    "ThreePointsMade": df_men["L_ThreePointsMade"],
    "ThreePointsAttempted": df_men["L_ThreePointsAttempted"],
    "FreeThrowsMade": df_men["L_FreeThrowsMade"],
    "FreeThrowsAttempted": df_men["L_FreeThrowsAttempted"],
    "OffensiveRebounds": df_men["L_OffensiveRebounds"],
    "DefensiveRebounds": df_men["L_DefensiveRebounds"],
    "Assists": df_men["L_Assists"],
    "Turnovers": df_men["L_Turnovers"],
    "Steals": df_men["L_Steals"],
    "Blocks": df_men["L_Blocks"],
    "PersonalFouls": df_men["L_PersonalFouls"],
    "L_TotalRebounds": df_men["L_TotalRebounds"],
    "L_ReboundPct": df_men["L_ReboundPct"],
    "L_OffensiveReboundPct": df_men["L_OffensiveReboundPct"],
    "L_DefensiveReboundPct": df_men["L_DefensiveReboundPct"],
})
loser_df.head(5)

According to previous winners, score marging is a good and strong indicator on team's potential to win. It's calculated by the difference in points scored between a team and its oppnents over a season.

In [ ]:
winner_df["MarginScore"] = winner_df["PointsFor"] - winner_df["PointsAgainst"]
loser_df["MarginScore"] = loser_df["PointsFor"] - loser_df["PointsAgainst"]

In [ ]:
winner_df["MarginScore"].head(5)

In [ ]:
loser_df["MarginScore"].head(5)

### Aggreagtions to check possible correlation between these numbers and win or loss

In [ ]:
winner_df_stats = winner_df.groupby([
    "Season",
    "TeamID",
], as_index=False).agg({
    "Win": "sum",
    "PointsFor":"mean",
    "PointsAgainst":"mean",
    "MarginScore":"mean",
    "FieldGoalsMade":"mean",
    "FieldGoalsAttempted":"mean",
    "ThreePointsMade":"mean",
    "ThreePointsAttempted":"mean",
    "FreeThrowsMade":"mean",
    "FreeThrowsAttempted":"mean",
    "OffensiveRebounds":"mean",
    "DefensiveRebounds":"mean",
    "Assists":"mean",
    "Turnovers":"mean",
    "Steals":"mean",
    "Blocks":"mean",
    "PersonalFouls":"mean"
})
winner_df_stats.head(5)

In [ ]:
loser_df_stats = loser_df.groupby([
    "Season",
    "TeamID",
], as_index=False).agg({
    "Win": "count",
    "PointsFor":"mean",
    "PointsAgainst":"mean",
    "MarginScore":"mean",
    "FieldGoalsMade":"mean",
    "FieldGoalsAttempted":"mean",
    "ThreePointsMade":"mean",
    "ThreePointsAttempted":"mean",
    "FreeThrowsMade":"mean",
    "FreeThrowsAttempted":"mean",
    "OffensiveRebounds":"mean",
    "DefensiveRebounds":"mean",
    "Assists":"mean",
    "Turnovers":"mean",
    "Steals":"mean",
    "Blocks":"mean",
    "PersonalFouls":"mean"
})
loser_df_stats.rename(columns={"Win": "Losses"}, inplace=True)
loser_df_stats.head(5)

In [ ]:
winner_df_stats.to_csv("../data/m_winner_df_stats.csv", index=False)
loser_df_stats.to_csv("../data/m_loser_df_stats.csv", index=False)

# @Dan and @Jason working on spotting possible correlations between win and everything else

# TODO:
- What's the correlation between win vs teams? - Using Orange Data Mining for this

# TODO:
- Can we add conferences to our main df? Then we can analyze how the conference affects the winning/losing team

- `MConferenceTourneyGames` has information such as conf abbreviation, wteam, lteam
- `Conferences` has the abbreviation and the actual name
- `MTeamConferences` has the team, the season, and its conference

Can we split the df into winners and losers teams and analyze them? Or maybe we can transform the df into long format

### TODO: We need to add conference information, as teams playing away may be in disadvantage

I'm still confused about seeds information and how to properly use them

### TODO:
- Recommended to me to find the FieldGoal percentage
- Free Throws percentage
- Turnover percentage
- Total rebounds
- Assists turnover ratio
- Rebound percentage

- For th TODOS above, we are going back to the initial dfs

In [ ]:
games_men = pd.concat([winner_df, loser_df], ignore_index=True)
games_men.head()

# FieldGoals Percentage @Gabe
`FG%=FGM / FGA`

In [ ]:
games_men["FieldGoalsPct"] = games_men["FieldGoalsMade"] / games_men["FieldGoalsAttempted"]
#games_women["FieldGoalsMade"] = games_women["FieldGoalsMade"] / games_women["FieldGoalsAttempted"]
games_men["FieldGoalsPct"].head(5)

# 3 Points Percentage @Gabe
`3P% = 3PM/3PA`

In [ ]:
games_men["ThreePointsMadePct"] = games_men["ThreePointsMade"] / games_men["ThreePointsAttempted"]
games_men["ThreePointsMadePct"]

# Free throws percentage @Gabe
`FT% = FTM / FTA`

In [ ]:
games_men["FreeThrowPct"] = games_men["FreeThrowsMade"] / games_men["FreeThrowsAttempted"]
games_men["FreeThrowPct"].head(5)

# Turnover percentage @ Gabe
`TO% = TO / FGA + 0.44 * FTA + TO`

In [ ]:
games_men["TurnoverPct"] = games_men["Turnovers"] / (games_men["FieldGoalsAttempted"] + 0.44 * games_men["FreeThrowsAttempted"] + games_men["Turnovers"])
games_men["TurnoverPct"].head(5)

# Total rebound @Dan
`TRB = OR + DR`
- Calculated before

# Rebound percentage @Dan
`REB% = REB / REB + oppREB`
- Done before merging!

# Assist turnover ratio @Gabe
` AST/TO = AST / TO`

In [ ]:
games_men["AssistTurnoverRto"] = games_men["Assists"] / games_men["Turnovers"]
games_men["AssistTurnoverRto"].head(5)

# Points per game @Gabe

In [ ]:
games_men["TtlPoints"] = games_men["PointsAgainst"] + games_men["PointsFor"]
games_men["TtlPoints"].head(5)

# Offensive rebound percentage @Dan
` or% = offReb / offReb + oppDefReb`
- Done before merging

In [ ]:
df_men["W_OffRebPct"] = df_men["W_OffensiveRebounds"] / (
    df_men["W_OffensiveRebounds"] + df_men["L_DefensiveRebounds"]
)

df_men["L_OffRebPct"] = df_men["L_OffensiveRebounds"] / (
    df_men["L_OffensiveRebounds"] + df_men["W_DefensiveRebounds"]
)

# Defensive rebound % @Dan
`DR% = defReb / defReb + oppOffReb`
- Done before merging

In [ ]:
df_men["W_DefRebPct"] = df_men["W_DefensiveRebounds"] / (
    df_men["W_DefensiveRebounds"] + df_men["L_OffensiveRebounds"]
)

df_men["L_DefRebPct"] = df_men["L_DefensiveRebounds"] / (
    df_men["L_DefensiveRebounds"] + df_men["W_OffensiveRebounds"]
)

# Possessions @Hafsa
`Poss = FGA - OR + TO + 0.44 * FTA`

In [ ]:
games_men["Possessions"] = (
    (games_men["FieldGoalsAttempted"]- games_men["OffensiveRebounds"] + games_men["Turnovers"] + 0.44 * games_men["FreeThrowsAttempted"]
     ))

games_men["Possessions"].head()

# Offensive efficiency @Hafsa
`offRating = Points / Possesion`

In [ ]:
games_men["OffEfficiency"]= games_men["PointsFor"] / games_men["Possessions"]
games_men["OffEfficiency"].head()

# Defensive efficiency @Hafsa
defRating = OppPoints / Possessions

In [ ]:
games_men["DefEfficiency"]= games_men["PointsAgainst"] / games_men["Possessions"]
games_men["DefEfficiency"].head()

# Net efficiency @ Hafsa
`NetRating = offRating - defRating`

In [ ]:
games_men["NetRating"] = games_men["OffEfficiency"] - games_men["DefEfficiency"]
games_men["NetRating"].head()

# Team win percentage @Gabe
`wins = wins / games`

# Strength of schedule @Gabe
- Gonna investigate how to do this

# Games played @Gabe

# Add conference information @Anyone???
- So we can figure out which games were away and which ones were home

# Seed  @Anyone???
- Create a seed difference